services:
  cypher:
    container_name: mcp-neo4j-cypher
    image: mcp-neo4j-cypher:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import neo4j; driver = neo4j.GraphDatabase.driver('${N4J_URL}', auth=('${N4J_USERNAME}', '${N4J_PASSWORD}')); driver.verify_connectivity(); driver.close()"]
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s 
    command: mcp-neo4j-cypher --db-url "${N4J_URL}" --username "${N4J_USERNAME}" --password "${N4J_PASSWORD}"
    networks:
      - ais-hypernova_default
      - mcp-neo4j-bridge-network
    restart: unless-stopped

networks:
  ais-hypernova_default:
    external: true
  mcp-neo4j-bridge-network:
    driver: bridge
